# Logger
exp_name: discrete_sac
record_interval: 1

# Environment
task: CartPole-v1
frame_skip: 1
from_pixels: false
reward_scaling: 1.0
init_env_steps: 1000
seed: 42

# Collector
env_per_collector: 5
max_frames_per_traj: 200
total_frames: 1000000
init_random_frames: 5000
frames_per_batch: 1000 # 500 * env_per_collector

# Replay Buffer
prb: 0
buffer_size: 100000

# Optimization
gamma: 0.99
batch_size: 256
lr: 3.0e-4
weight_decay: 0.0
target_update_polyak: 0.995
target_entropy_weight: 0.2

device: cpu